layout_spectrum: 0.8914894
typography_spectrum: 0.5787234
color:
  saturation: 0.7217595
  lightness: 0.2574468
  brandStrength: 0.6473336
  brandColors:
    - '#FFFFFF'
    - '#C9DA66'
    - '#64635E'
    - '#1A1704'
    - '#8AA746'
  rhythmicContrast: 0.6514786
name: illkind
