layout_spectrum: 0.8914894
color:
  saturation: 0.9446809
  lightness: 0.5234042
  brandStrength: 0.6473336
  brandColors:
    - '#FFFFFF'
    - '#C9DA66'
    - '#64635E'
    - '#1A1704'
    - '#8AA746'
  rhythmicContrast: 0.8340425
typography_spectrum: 0.5787234
name: illkind
